<?php 

namespace App\Models\Examen;

use CodeIgniter\Model;

class ExamenModel extends Model
{
    protected $table = 'rapportexamenmedical';
    protected $primaryKey = 'ExamenId';
    protected $allowedFields = [
        'etablissement',
        'genre',
        'nomPrenom',
        'dateNaiss',
        'profession',
        'adresse',
        'dateExamen',
        'docteurExamen',
        'poids',
        'taille',
        'TAG',
        'IMC',
        'TAD',
        'avantCorrectionOD',
        'avantCorrectionOG',
        'apresCorrectionOD',
        'apresCorrectionOG',
        'acuiteAuditive',
        'antecedentMedicauxPersonnels',
        'antecedentMedicauxFamiliaux',
        'antecedentChirurgicaux',
        'antecedentGynecoObsetrique',
        'aspectSainAgeIndique',
        'malformationMutilations',
        'commentairesAspectGeneral',
        'goitre',
        'languePharynxAmygdalesAnormale',
        'affectionYeux',
        'affectionAuditif',
        'commentaireORL_OPHTALMOLOGIE',
        'affectionBuccoDentaire',
        'etatDentaire',
        'commentaireStomatologieque',
        'respiratoireLimite',
        'percussionAnormales',
        'ausculationAnormaux',
        'voixVoilee',
        'commentairesRespiratoire',
        'bruitsCoeuModifie',
        'souffleCardiaque',
        'poulesInferieursPercus',
        'souffleArteresCervicales',
        'commentairesCardioVasculaire',
        'palpationPathologique',
        'hepatomegalie',
        'splenomegalie',
        'hernie',
        'hemorroide',
        'commentairesDigestif',
        'alcoolismeTabagisme',
        'antecedentsOrganesGenito',
        'indicesAffectionOrganesGenitauxM',
        'indicesAffectionOrganesGenitauxF',
        'gynecomastie',
        'modificationAnormalSeins',
        'commentairesGenitoUrinaire',
        'urineAspect',
        'urineAlbumine',
        'urineGlucose',
        'urineLEU',
        'urineNIT',
        'urineSG',
        'urinePH',
        'urinePRO',
        'urineKET',
        'urineURO',
        'reflexePupillaires',
        'signesDystonie',
        'troublesPsychique',
        'commentairesSystemeNerveux',
        'ictereCyanose',
        'eruptionUlcerationKyste',
        'ganglionsLymphatiques',
        'cicatricesTatouages',
        'tophusXanthome',
        'commentairespeau',
        'affectionOs',
        'commentairesSquelette',
        'repercussionProffessionelles',
        'commentairesRepercussionProfessionnelles',
        'etatSanteConsidere',
        'remarquesSpeciales',
        'villeExamen',
        'etatExamen',
        'isDeleted'
    ];
    protected $useTimestamps = true;
    protected $createdField = 'createdAt';
    protected $updatedField = 'updatedAt';
}